services:
  postgres:
    image: postgres:16.13-alpine
    container_name: ku-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ku_app
      POSTGRES_USER: ku_user
      POSTGRES_PASSWORD: ku_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ku_user -d ku_app"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:8.6.2-alpine
    container_name: ku-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10


volumes:
  postgres_data:
  redis_data:
